### ISSUE TITLE
怎么在railway上免费部署

### ISSUE THREAD

**Issue by endandleaf** [ystyle/kaf-cli#11]
我发现阅读3.0可以railway.在railway上免费部署之后，想利用railway也来部署kas，但是构建失败，感觉命令里是不是必须要kindlegen啊。railway
![QQ截图20220524101335](https://user-images.githubusercontent.com/33244808/169934652-07556722-02ce-4944-958f-f7f434e3b14d.png)
.

**Comment by endandleaf** [comment]
部署的是KAS那个

**Comment by ystyle** [comment]
kindlegen是用来生成mobi格式的，不需要可以去掉
仓库： https://github.com/ystyle/kas

**Comment by ystyle** [comment]
报错是因为官方不支持下载kindlegen了， 可以用镜像站下载
https://archive.org/download/kindlegen2.9/kindlegen_linux_2.6_i386_v2_9.tar.gz

**Comment by endandleaf** [comment]
> kindlegen是用来生成mobi格式的，不需要可以去掉 仓库： https://github.com/ystyle/kas

我是fork的那个仓库，但是railway不能下载kindlegen，只能自动部署，想和arm版本一样只用来转epub，

**Comment by endandleaf** [comment]
想着和arm版一样不需要其他软件就能在docker里运行

**Comment by ystyle** [comment]
我已经把下载地址换成新的了

**Comment by endandleaf** [comment]
是吗，我再试一下，谢谢大佬

**Comment by endandleaf** [comment]
还是报错，应该是railway不支持下载外部文件
![image](https://user-images.githubusercontent.com/33244808/169937659-d9e7ce82-f49d-485a-97e5-32e077cdd5b9.png)

**Comment by ystyle** [comment]
或者你fork一份，把框里的删除
![image](https://user-images.githubusercontent.com/4478635/169937830-4bd1beda-c6b9-4466-a17e-1253194eb575.png)

**Comment by endandleaf** [comment]
好的

**Comment by endandleaf** [comment]
啊这...
![image](https://user-images.githubusercontent.com/33244808/169938759-bd1468f3-c750-4010-97dc-534ae0e1ae8c.png)

**Comment by ystyle** [comment]
不支持多阶段构建么。。。改为一个的试试。。。
```dockerfile
FROM golang:alpine AS build-env
ENV GO111MODULE=on
ADD . /go/src/app
WORKDIR /go/src/app
RUN apk --update add git curl tzdata && \
    go build -v -o /go/src/app/kas main.go && \
    export GO111MODULE=off && \
    go get github.com/GeertJohan/go.rice && \
    go get github.com/GeertJohan/go.rice/rice && \
    rice append --exec kas 
VOLUME ["/go/src/app/storage"]
EXPOSE 1323
HEALTHCHECK --interval=1m --timeout=10s \
  CMD curl -f http://localhost:1323/ping || exit 1
CMD ./kas
```

**Comment by endandleaf** [comment]
成功了，我试试速度怎么样
![image](https://user-images.githubusercontent.com/33244808/169941354-bec5d901-a65a-4127-91a2-8c510b30e6ec.png)

**Comment by endandleaf** [comment]
话说漫画地址是不是没用了啊

**Comment by ystyle** [comment]
> 话说漫画地址是不是没用了啊

太久了，没用了。。。网站也改版了。。。那个转漫画的界面现在没什么用。。。

**Comment by endandleaf** [comment]
网站能打开，手机KAF连接不上是什么原因呢
![image](https://user-images.githubusercontent.com/33244808/169942077-19b9b0f6-2984-4108-929c-4c301aa58b7a.png)

**Comment by ystyle** [comment]
开启了 https 的话， 手机连接是： wss://kas.kindlekaf.cf

**Comment by endandleaf** [comment]
不行，改这个地址也连接不上

**Comment by ystyle** [comment]
不好意思少打了路径： wss://kas.kindlekaf.cf/ws

**Comment by endandleaf** [comment]
可以了，谢谢大佬，速度有2M/S多，够用了
