### ISSUE TITLE
用命令行插入封面有问题

### ISSUE THREAD

**Issue by ranqianchen** [ystyle/kaf-cli#13]
> 首先我是小白，我尽力表达
在我电脑里我是这么写的
.\kaf-cli -format "epub" -lang "zh" -cover "cover.png" -filename E:\LCL\Documents\novel/《朕的爱妃只想吃瓜》作者：延琦.txt
转换出来的epub文件是0kb
但是当我用直接拖入的时候，epub是正常生成且带封面的

就。。
挺奇怪的

**Comment by carlzhc** [comment]
试一下将文件名用双引号括起来。

ranqianchen ***@***.***> 于 2022年11月3日周四 下午2:25写道：

**Comment by ranqianchen** [comment]
![Snipaste_2022-11-04_22-49-56](https://user-images.githubusercontent.com/65606785/200005224-147c5eef-74d9-49f4-a154-7b9f4e4e3bef.png)
但不加封面就有效
![Snipaste_2022-11-04_22-54-05](https://user-images.githubusercontent.com/65606785/200005734-1710ff95-a745-49c2-8af8-17280d332482.png)
其实也没啥，反正通过邮箱传到kindle也没封面（笑死）

**Comment by ystyle** [comment]
其实你是文件名打的有问题,  文件名问题： 
如果你的文件就在当前目录就直接按键盘上的tab键就可以自动补全，补全的文件名不会错
或者你直接拖文件名到命令行工具里，一般也会自动拼好的

```powershell
PS E:\Kindle\电子书\一块板砖闯仙界> kaf-cli.exe -format epub -lang cn -cover .\1ca680a5361634c6536706505480c5c5ec972ea6.jpg -filename .\《一块板砖闯仙界》（校对版全本）作者：妖天.txt
转换信息:
软件版本: v1.2.7
文件名:  .\《一块板砖闯仙界》（校对版全本）作者：妖天.txt
书籍书名: 一块板砖闯仙界
书籍作者: 妖天
书籍封面: .\1ca680a5361634c6536706505480c5c5ec972ea6.jpg
书籍语言: en
匹配条件: 自动匹配
转换格式: epub

正在读取txt文件...
读取文件耗时: 302.1642ms
匹配章节: 745

正在生成epub
正在生成电子书...
生成EPUB电子书耗时: 1.6537917s


转换完成! 总耗时: 1.6710441s
```

**Comment by ranqianchen** [comment]
拖拽文件名尝试完毕，依然没有用，我close了，自闭了，睡觉

**Comment by ystyle** [comment]
可以了， 之前的问题是， 用全路径时读取图片会失败。 直接在目录下的不会（上面的例子）
下载v1.2.9版本就行了

**Comment by ranqianchen** [comment]
下了新的，可以了
ohhhhhhhhh
