### ISSUE TITLE
求一个精简版

### ISSUE THREAD

**Issue by ShrekCharles716** [ystyle/kaf-cli#20]
求一个精简版，只需要生成epub格式的文本功能即可，不需要azw3、mobi文件。

**Comment by ShrekCharles716** [comment]
为什么会生成3个azw3文件
![image](https://user-images.githubusercontent.com/112491914/213273273-ed5c0c3c-2bef-442d-b505-b0fcc3026896.png)

**Comment by ystyle** [comment]
现在有三种方法可以做到只生成指定格式的：
1. 下载最新版， 然后在环境变量添加`KAF_CLI_FORMAT = epub` (windows上打开环境变量是win+s快捷键搜索`编辑环境变量`)
2. 用命令行模式： `./kaf-cli -author 乱 -filename ./全职法师.txt -format epub` ， -format参数
3. 看到 `生成EPUB电子书耗时: xxxx`时就可以关闭软件了，epub已经生成了

**Comment by ShrekCharles716** [comment]
> 现在有三种方法可以做到只生成指定格式的：
> 
> 1. 下载最新版， 然后在环境变量添加`KAF_CLI_FORMAT=epub` (windows上打开环境变量是win+s快捷键搜索`编辑环境变量`)
> 2. 用命令行模式： `./kaf-cli -author 乱 -filename ./全职法师.txt -format epub` ， -format参数
> 3. 看到 `生成EPUB电子书耗时: xxxx`时就可以关闭软件了，epub已经生成了
我下载了最新的v1.2.11,使用第一种方式配置了path变量，复制了这段命令”KAF_CLI_FORMAT=epub“还是生成了其他格式
![image](https://user-images.githubusercontent.com/112491914/215241254-6bf8c4b7-c894-4f2a-8f5e-e82b8b54a597.png)
是我环境变量没配置好吗

**Comment by ystyle** [comment]
是的，你这个应该直接放和path同级就好了，在用户和系统的都行。

**Comment by ShrekCharles716** [comment]
![image](https://user-images.githubusercontent.com/112491914/215249825-bf5bd10e-3590-49ff-9942-50b32024b569.png)
是这样吗，试过了，也没用

**Comment by ystyle** [comment]
不是这样，下面：
变量名填：`KAF_CLI_FORMAT` 
变量值填: `epub`

**Comment by ShrekCharles716** [comment]
谢谢大佬解惑，问题解决了
