### ISSUE TITLE
命令行关闭制作教程怎么去掉说明两个字

### ISSUE THREAD

**Issue by ShrekCharles716** [ystyle/kaf-cli#23]
就两个字占了一页空间，看着好不爽
![图片](https://user-images.githubusercontent.com/112491914/216739844-ecbd3a34-7871-4dee-9220-615b5c0908a4.png)

**Comment by ystyle** [comment]
把小说发我看看。 
默认如果第一章前面，如果有不为空的行，就会加一个说明的章节， 把内容放进去。
你这个看起来是有一个中文空格、隐藏字符之类的行

**Comment by ShrekCharles716** [comment]
没有空行
[蘑菇屋：扮演藤哥！整蛊百万观众.txt](https://github.com/ystyle/kaf-cli/files/10594770/default.txt)

**Comment by ystyle** [comment]
可以了，下载v1.2.12版本就行了

**Comment by ShrekCharles716** [comment]
大佬，太给力了，不过右键菜单ps文件怎么使用啊

**Comment by ShrekCharles716** [comment]
直接PowerShell运行吗，我运行之后，PowerShell一闪就关闭了，右键txt也没看见转换菜单

**Comment by ShrekCharles716** [comment]
大佬有没有时间实现一个kaf-cli指令生成器，具体实现就是在cmd中输入命令行参数：作者、封面、书籍格式等参数，保存到变量中，最后字符串拼接变量把kaf-cli指令打印在cmd中，这样小白也会用。我用python实现了这个效果，效果如下图
![image](https://user-images.githubusercontent.com/112491914/216789014-6a78a3fc-9cb5-4b62-b0d2-3c1d1dfd87c7.png)
想分享出来，使用pyinstaller打包exe，运行exe输入完参数就程序结束cmd窗口关闭了，没机会复制指令

**Comment by ShrekCharles716** [comment]
语言设置这个功能有什么用，是可以将其他英语文本转换为中文吗

**Comment by ystyle** [comment]
> 语言设置这个功能有什么用，是可以将其他英语文本转换为中文吗

这个是元数据，用来搜索或标记书籍是什么语言的，一般没什么用，但部分阅读器，比如kindle会控制只能换对应语言的字体。 比如选择了英文，在阅读器上就换不了中文字体了

**Comment by ystyle** [comment]
> 直接PowerShell运行吗，我运行之后，PowerShell一闪就关闭了，右键txt也没看见转换菜单

我这边直接右键使用PowerShell运行运行就好了，会弹一个请求管理权限的授权窗口，选择是然后会打开一个是否注册成功的窗口。

如果不行，搜索PowerShell右键以管理员方式打开，然后把右键菜单脚本拖过去回车试试。 如果没执行权限，好像会打印一个命令让你授权
