### ISSUE TITLE
这两天安卓版转换不了(⁠〒⁠﹏⁠〒⁠)

### ISSUE THREAD

**Issue by key147** [ystyle/kaf-cli#26]
求求大大，是服务器换了吗•́⁠ ⁠ ⁠‿⁠ ⁠,⁠•̀

**Comment by ystyle** [comment]
你看看服务器是不是
wss://kas.ystyle.top/ws




发自我的手机


-------- 原始邮件 --------
发件人： key147 ***@***.***>
日期： 2023年2月26日周日 22:50
收件人： ystyle/kaf-cli ***@***.***>
抄送： Subscribed ***@***.***>
主 题： [ystyle/kaf-cli] 这两天安卓版转换不了(⁠〒⁠﹏⁠〒⁠) (Issue #26)

求求大大，是服务器换了吗•́⁠ ⁠ ⁠‿⁠ ⁠,⁠•̀

**Comment by key147** [comment]
好了！谢谢！
