### ISSUE TITLE
求新功能

### ISSUE THREAD

**Issue by ShrekCharles716** [ystyle/kaf-cli#27]
1. 求添加`epub` → `txt`互转功能，在接触kaf之前一直都是使用本地txt阅读器看小说，优点：没有广告，app体积小，启动速度快，缺点：没有书源，需要手动导入txt、界面简陋、功能太少。后面无意发现ios自带图书软件`apple books`可以导入epub格式，使用体验感远超之前使用的txt阅读器。便换成`books`阅读小说，将所有收集的资源一次性都转换成了epub格式。这些资源大多都是从盗版网站下载的txt文本，有好多广告信息、错别字等无用字符，想修改替换掉。百度查询后发现编辑epub文本非常麻烦，且效率低。之前转换epub前考虑后面不会在使用txt阅读，都删了只留了epub文本。重新从网上下载一个个找txt资源效率太低，且许多小众资源都搜索不到，都是之前无意中一点点收集的。网上有在线转换网站，但发现转换太慢，且转换后的文本换行格式全乱了，体验很差。所以希望作者可以抽空开发`epub` → `txt`互转功能。
2. 添加一个新规则，将章节名称格式修改为 第xx章 xxxx，例如原标题`001 xxx` 修改后 `第001章 xxx`

**Comment by ystyle** [comment]
第1个，其实可以用[Sigil](https://github.com/Sigil-Ebook/Sigil/releases),  打开epub后，随便打开一个文件，右键重新对html格式化- 对所有的html文档格式化。 然后再查找替换就行了。

**Comment by ShrekCharles716** [comment]
我百度搜索到的也是这个sigil，不是很会用，只能一个网页一个网页的修改替换，不能一次性替换所有网页内容，效率太慢

**Comment by ystyle** [comment]
搜索面板正面选择一下所有html文档就好了




发自我的手机


-------- 原始邮件 --------
发件人： ShrekCharles716 ***@***.***>
日期： 2023年3月13日周一 19:29
收件人： ystyle/kaf-cli ***@***.***>
抄送： "YSTYLE-L.X.Y" ***@***.***>, Comment ***@***.***>
主 题： Re: [ystyle/kaf-cli] 求新功能 (Issue #27)

我百度搜索到的也是这个sigil，不是很会用，只能一个网页一个网页的修改替换，不能一次性替换所有网页内容，效率太慢

―

**Comment by ShrekCharles716** [comment]
![image](https://user-images.githubusercontent.com/112491914/226288764-edd48b2f-6df5-45c2-b789-9a06df2bcf48.png)
可以实现这样的二级目录效果吗

**Comment by ShrekCharles716** [comment]
大佬，kaf正则语法有bug
![image](https://user-images.githubusercontent.com/112491914/226826171-5b8f7162-e9f0-4e74-91a8-b283d6432e1b.png)
我在命令行标题匹配条件中使用了`^`匹配行首字符以第开头的标题，可运行后`^`并没有生效
![image](https://user-images.githubusercontent.com/112491914/226827671-fb563c67-88ba-4e30-8fd9-fce2d4059c13.png)

**Comment by ystyle** [comment]
> 大佬，kaf正则语法有bug ![image](https://user-images.githubusercontent.com/112491914/226826171-5b8f7162-e9f0-4e74-91a8-b283d6432e1b.png) 我在命令行标题匹配条件中使用了`^`匹配行首字符以第开头的标题，可运行后`^`并没有生效 ![image](https://user-images.githubusercontent.com/112491914/226827671-fb563c67-88ba-4e30-8fd9-fce2d4059c13.png)

你这个可以写 `-match  "^第.{1，8}章"` 加上引号

**Comment by ystyle** [comment]
> ![image](https://user-images.githubusercontent.com/112491914/226288764-edd48b2f-6df5-45c2-b789-9a06df2bcf48.png) 可以实现这样的二级目录效果吗

这个，以后有时间可能会加，现在我用的epub生成工具已经有这功能了。 但azw3和mobi的没这功能，所以就只会支持epub格式的

**Comment by ystyle** [comment]
新版本已经支持二级目录
