### ISSUE TITLE
有一点小问题

### ISSUE THREAD

**Issue by wppepewy** [ystyle/kaf-cli#28]
你好，转换过程中出现警告 错误使用 什么什么 <link>之类的是什么原因，有什么影响吗

**Comment by wppepewy** [comment]
<link>啥的

**Comment by wppepewy** [comment]
“<link>”之类的

**Comment by wppepewy** [comment]
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>

**Comment by wppepewy** [comment]
生成出来的目录只有chapter;没有章节序号和章节名

**Comment by ystyle** [comment]
> 警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为：

没影响

**Comment by ystyle** [comment]
> 生成出来的目录只有chapter;没有章节序号和章节名

把小说发来看看

**Comment by wppepewy** [comment]
应该是章节名格式不对吧，他这个小说章节名格式是“===第一章 惊蛰===”，首尾是===，我换了一个没等号的就可以了
