### ISSUE TITLE
这个日文小说匹配不了章节

### ISSUE THREAD

**Issue by icearchimage** [ystyle/kaf-cli#29]
不知为何就是不识别，一开始用的是`\[\d{4}\]`，不识别，然后我把每个章节前面的一个特殊字符批量替换成了“第1节”，这个第1节居然也识别不了。用的是1.2.12版。

[test.txt](https://github.com/ystyle/kaf-cli/files/11611290/test.txt)

**Comment by ystyle** [comment]
`\[\d{4}\]` 和 `第1节`都是可以的, 问题出在日文小说把标题当简介写.  之前为了减少章节识别的错误率, 把标题字数限制默认改为了35(国内35基本上都能把错误的去掉了). 
你这个加上参数:  -max 100就能识别了

![image](https://github.com/ystyle/kaf-cli/assets/4478635/240f7252-4cc4-465e-a392-0ec88b3a6619)
![image](https://github.com/ystyle/kaf-cli/assets/4478635/19129f3d-96c4-4800-98f3-4f795558e8d2)

**Comment by icearchimage** [comment]
害，是我没看清楚说明里的参数，原来默认检测标题字数35，抱歉抱歉
