### ISSUE TITLE
可以将多个epub合并吗？

### ISSUE THREAD

**Issue by dianso** [ystyle/kaf-cli#3]

**Comment by dianso** [comment]
一个作者好多书，每个书都是txt，转换成epub，然后再合并，合并时候希望每本书有总目录，目录名就是书名。可以增加这个功能吗？

**Comment by ystyle** [comment]
感觉这功能不是很必要。。。而且我用的这个epub生成器不支持多级目录。
（合并多了感觉很容易超了大小吧。。。
如果管理的话，可以用kindle的收藏夹或直接用calibre管理（calibre也有合并多本书的功能
