### ISSUE TITLE
关于2级目录的问题

### ISSUE THREAD

**Issue by Jay021** [ystyle/kaf-cli#30]
作者你好，

我是 "kaf-cli" 的用户，我对你的软件非常感兴趣，非常感谢你开发出如此实用的工具，并在最近更新中增加了“二级目录”功能。
最近，我在尝试使用该功能时遇到了一个问题，希望能向你反馈并寻求解决方案。
具体如下：

我的文本目录结构为：

> 第一部
> 第一章、第二章、第三章、第四章……
> 
> 第二部
> 第一章、第二章、第三章、第四章……

以此类推。

kaf-cli 在“二级目录”匹配时，会把“第一部”的最后一章，错误的放在了“第二部”的第一章。

<img width="1468" alt="Snipaste_2023-06-27_19-54-13" src="https://github.com/ystyle/kaf-cli/assets/20473663/2f2d3e56-7db1-4716-8123-fa21bed4396b">

我注意到 kaf-cli 的默认正则可以识别“卷”，无法识别“部”；
为了排除是否因为我的命令出了问题，我又做了测试，把标题改为“第一卷”、“第二卷”……，把文本拖拽到 kaf-cli 上，以完全自动识别，依然是此结果。

此问题让我有些困扰，因此非常希望能得到你的帮助。如果你需要更多信息，或者我可以做些什么来帮助你调试和解决这个问题，请随时告诉我。

再次感谢你提供如此出色的软件，它为我在制作EPUB小说时，提供了巨大的帮助和便利。

望回复为盼。

**Comment by ystyle** [comment]
把你这txt发我一下， 我没那么短的。有点难测试

**Comment by Jay021** [comment]
[测试1.txt](https://github.com/ystyle/kaf-cli/files/11881837/1.txt)

**Comment by ystyle** [comment]
这个应该好了。1.3.1

**Comment by Jay021** [comment]
非常感谢你这么迅速的修复了问题，但我在测试中仍然遇到了一些错误。具体如下：
文本内容中，“第一部”的正文内容，会被放到“章节正文”里，而“第二部”的正文，会沿用“第一部”最后一章的标题。
每个一级标题里，正文都未被放在正确的位置。

<img width="1020" alt="Snipaste_2023-06-28_00-22-50" src="https://github.com/ystyle/kaf-cli/assets/20473663/3201361b-1212-4958-ab26-77d7f2577d4c">
<img width="1020" alt="Snipaste_2023-06-28_00-23-15" src="https://github.com/ystyle/kaf-cli/assets/20473663/a0465b6c-89db-4963-ac11-221a4ddd1fbc">
<img width="1019" alt="Snipaste_2023-06-28_00-23-30" src="https://github.com/ystyle/kaf-cli/assets/20473663/f03249d8-0c87-4cd4-8176-d1f7bf553db2">

**Comment by TingTing1990** [comment]
支持2级目录已经完美了，楼主测试也很仔细啊，如果是部的话，"^第[0-9一二三四五六七八九十零〇百千两 ]+卷"  的+卷改为+部吗？

**Comment by ystyle** [comment]
试试1.3.2

**Comment by Jay021** [comment]
> 支持2级目录已经完美了，楼主测试也很仔细啊，如果是部的话，"^第[0-9一二三四五六七八九十零〇百千两 ]+卷" 的+卷改为+部吗？

作者在1.3.1版本支持“部”了，我在1.3.0使用的命令为 -volumematch "^第[一二三四五六七八九十零〇百千两 ]+部 "。
<img width="866" alt="微信截图_20230628111805" src="https://github.com/ystyle/kaf-cli/assets/20473663/d2a9422a-5a66-4182-8039-fa8359920f9a">

另外，我还会在正则最后，添加一个空格，以避免正文的内容被识别到标题里。这些都要根据不同的文本，自己修改正则。

<img width="1284" alt="微信截图_20230628111715" src="https://github.com/ystyle/kaf-cli/assets/20473663/e928cedf-2f9e-45ba-8bc7-a158700836e2">

目前，1.3.2 完美了！

**Comment by Jay021** [comment]
> 试试1.3.2

我再次测试了软件，所有问题都彻底解决。kaf-cli 的二级目录识别功能，现在非常稳定可靠和出色！

我真的非常非常感谢！

**Comment by TingTing1990** [comment]
完美，再次感谢！
