### ISSUE TITLE
新功能使用问题

### ISSUE THREAD

**Issue by ShrekCharles716** [ystyle/kaf-cli#33]
求指点该命令行指令是否有问题
`kaf-cli.exe -align center -author 卖报小郎君 -cover [卖报小郎君]大奉打更人.jpg -filename [卖报小郎君]大奉打更人.txt -line-height 1rem -match "^第.{1,8}章" -max 35 -format epub -volume-match "^第[0-9一二三四五六七八九十零〇百千两 ]+[卷部]" -tips=false`
我在测试`二级目录`的时候，发现在命令行模式下`标题匹配条件`和`卷匹配条件`两者不能共存，只能保留一个，`-volume-match string`会失效，卷名称会被识别为`章节正文`。
![image](https://github.com/ystyle/kaf-cli/assets/112491914/968e0176-7436-4bf1-a085-862850df28cf)
如果去除`标题匹配规则`，可以识别出`卷`目录，但没有达到`二级目录`的效果，只是将`一级目录卷`识别为同级的`标题`
![image](https://github.com/ystyle/kaf-cli/assets/112491914/c4eded3f-7f76-4e19-b7e3-70511ee41dcc)
经过测试，可以排除掉app（SumatraPDF）不支持二级目录的可能性
![image](https://github.com/ystyle/kaf-cli/assets/112491914/b4259bb4-432b-481d-8ef2-bbbffda76c7b)

**Comment by ystyle** [comment]
1.  章节的匹配规则要同时能匹配章节和卷， 然后卷是在匹配出的章节结果里二次匹配出来的
2. 字体可以用`kaf-cli -filename 1.txt  -font 字体文件名.ttf `

**Comment by ShrekCharles716** [comment]
1. 我将指令改了一下，可是还没能实现二级目录效果
`kaf-cli.exe -align center -author 卖报小郎君 -cover [卖报小郎君]大奉打更人.jpg -filename [卖报小郎君]大奉打更人.txt -line-height 1rem -match "^第.{1,8}[章卷部]" -max 35 -format epub -volume-match "^第[0-9一二三四五六七八九十零〇百千两 ]+[卷部]" -tips=false`
![image](https://github.com/ystyle/kaf-cli/assets/112491914/868c9256-ad57-478c-bb13-1ec2aa8ededa)
2. 字体命令指令是这些写吗
`kaf-cli -filename [卖报小郎君]大奉打更人.txt -font 微软雅黑.ttf`

**Comment by ystyle** [comment]
把你的txt发一下我看看。

字体要自己下载，路径指向下载的字体文件

**Comment by ystyle** [comment]
用你同样的参数，奥术神座是可以的
![image](https://github.com/ystyle/kaf-cli/assets/4478635/7fbd0de3-7721-426b-b963-0a78ff31c1b5)

**Comment by ystyle** [comment]
字体使用方式，和上面那张对比一下字体显示 
![image](https://github.com/ystyle/kaf-cli/assets/4478635/90f1be83-c31e-4c18-9a57-baafd9ffbe8d)

**Comment by ShrekCharles716** [comment]
好的，多谢。
[[卖报小郎君]大奉打更人.txt](https://github.com/ystyle/kaf-cli/files/11990531/default.txt)
阅读器为`sumatra pdf`

**Comment by ystyle** [comment]
是你阅读器的问题吗？
![image](https://github.com/ystyle/kaf-cli/assets/4478635/ce60114e-c600-42f5-9ccb-7e14602a1e91)

**Comment by ystyle** [comment]
是你阅读器的问题吗？
![image](https://github.com/ystyle/kaf-cli/assets/4478635/8fb4d759-0469-415e-af0e-e274417c8c24)
[大奉打更人.zip](https://github.com/ystyle/kaf-cli/files/11990625/default.zip)

**Comment by ystyle** [comment]
手机的阅读器，也是支持的
![6300a8378f1972db4a89ae7d7921eb56](https://github.com/ystyle/kaf-cli/assets/4478635/ddcc85eb-c523-45e3-ae4c-33d9507614f5)

**Comment by ystyle** [comment]
阅读器的koreader
![0daf6a9348ac39ad1f7b9544ba507065](https://github.com/ystyle/kaf-cli/assets/4478635/ea1c8548-359f-4b67-aeaa-2238fc68380f)

**Comment by ShrekCharles716** [comment]
[SumatraPDF-3.4.6-x64.zip](https://github.com/ystyle/kaf-cli/files/11990922/SumatraPDF-3.4.6-x64.zip)
这个sumatra pdf绿色版双击exe运行，可以随时删除，你试试用这个app打开，我也怀疑过是阅读器问题，可我之前网络上下载了一本epub小说，阅读器是可以支持二级目录，上文我还发了截图，我手机端用的是apple books不支持二级目录，无法判断

**Comment by ShrekCharles716** [comment]
我刚刚试了网上的教程复制了win自带的仿宋字体文件，命令行指令转换后epub大小翻了近一倍，请问这正常吗。大奉打更人epub正常大小是6m，使用嵌入字体内存大小直接11m了。
大佬想问一下你PC端的阅读器是什么软件，免费无广吗

**Comment by ystyle** [comment]
> 我刚刚试了网上的教程复制了win自带的仿宋字体文件，命令行指令转换后epub大小翻了近一倍，请问这正常吗。大奉打更人epub正常大小是6m，使用嵌入字体内存大小直接11m了。 大佬想问一下你PC端的阅读器是什么软件，免费无广吗


你可以看看字体大小是多少， 一般是书大小+字体大小， 比如我的SourceHanSerifSC一个字体就有20多M,  多国语言完整版有100多M

**Comment by ystyle** [comment]
> [SumatraPDF-3.4.6-x64.zip](https://github.com/ystyle/kaf-cli/files/11990922/SumatraPDF-3.4.6-x64.zip) 这个sumatra pdf绿色版双击exe运行，可以随时删除，你试试用这个app打开，我也怀疑过是阅读器问题，可我之前网络上下载了一本epub小说，阅读器是可以支持二级目录，上文我还发了截图，我手机端用的是apple books不支持二级目录，无法判断

我pc用的是 calibre: https://github.com/kovidgoyal/calibre

**Comment by ystyle** [comment]
> 我刚刚试了网上的教程复制了win自带的仿宋字体文件，命令行指令转换后epub大小翻了近一倍，请问这正常吗。大奉打更人epub正常大小是6m，使用嵌入字体内存大小直接11m了。 大佬想问一下你PC端的阅读器是什么软件，免费无广吗

你这个不是专门的epub阅读器， 兼容性有问题， 有些支持有些不支持

**Comment by ystyle** [comment]
> [SumatraPDF-3.4.6-x64.zip](https://github.com/ystyle/kaf-cli/files/11990922/SumatraPDF-3.4.6-x64.zip) 这个sumatra pdf绿色版双击exe运行，可以随时删除，你试试用这个app打开，我也怀疑过是阅读器问题，可我之前网络上下载了一本epub小说，阅读器是可以支持二级目录，上文我还发了截图，我手机端用的是apple books不支持二级目录，无法判断

你这个不是专门的epub阅读器， 兼容性有问题， 有些支持有些不支持

**Comment by ystyle** [comment]
我上面截图的是calibre. 另外还有个叫 koodo-reader的， 也挺不错的，最近这个用的人也挺

https://github.com/troyeguo/koodo-reader


![image](https://github.com/ystyle/kaf-cli/assets/4478635/f5d27431-b268-4704-9d11-bb2fd0fb03af)

**Comment by ShrekCharles716** [comment]
![image](https://github.com/ystyle/kaf-cli/assets/112491914/f8285fdd-e0ba-414e-9dc0-6fb0fd4dcf2c)
![image](https://github.com/ystyle/kaf-cli/assets/112491914/adeac095-dea0-4aeb-8430-0cee412cc2a7)
确实是阅读器兼容性问题，有的支持二级目录，有的不支持。图一是网上下载的，图二是使用kaf-cli转换的。
已经换了阅读器，koodo-reader功能很强大，就是太重了不是很轻量，感谢大佬推荐。最后问题全部圆满解决

**Comment by ShrekCharles716** [comment]
> 手机的阅读器，也是支持的 ![6300a8378f1972db4a89ae7d7921eb56](https://private-user-images.githubusercontent.com/4478635/251974551-ddcc85eb-c523-45e3-ae4c-33d9507614f5.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NDc3MjgsIm5iZiI6MTcxNDg0NzQyOCwicGF0aCI6Ii80NDc4NjM1LzI1MTk3NDU1MS1kZGNjODVlYi1jNTIzLTQ1ZTMtYWU0Yy0zM2Q5NTA3NjE0ZjUuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDE4MzAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhYzUyYmY3MjE5YzJjZmNiZmZlMzUzY2Y4ZTcyNzY3ZmZkOGU4M2FmNTdlYTMzNmQyN2NkNWUzMDExZTVlYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hn8_YEaZARmXupOfu76h2hi0h0kw_0rcfKZh33yAo-s)

问一下，这个手机上的阅读器是什么软件。安卓有没有好用无广的本地epub阅读器

**Comment by ystyle** [comment]
> 问一下，这个手机上的阅读器是什么软件。安卓有没有好用无广的本地epub阅读器

我 这个是《华为阅读》，以前华为上的《阅读》也是一样的， 《掌阅/ireader》这三个都并不多，书城都会在每次打开弹推荐。
《起点》也可以。
网上很火的[阅读](https://github.com/gedoor/legado)可以订阅书源的这个也可以本地。这个就没广告，也没书城，但订阅个好源也有很多书。
