### ISSUE TITLE
-tips 添加本软件教程 命令行参数问题

### ISSUE THREAD

**Issue by xingzhili2007** [ystyle/kaf-cli#4]
## 测试环境
Darwin localhost 20.1.0 Darwin Kernel Version 20.1.0: root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64
## 问题
在Darwin上测试本项目时，发现无论如何都去不掉tips的内容，具体研究发现貌似在Darwin命令行传递参数是传递的是String类型的数据，最后到代码中会把string强制转换成bool,导致无法去掉tips
~~我当然是为了白嫖才会发现的~~

**Comment by ystyle** [comment]
在linux和windows我这么传是可以的（我没osx，没法直接调试了。。。）
```shell
# kaf-cli -author 一念乱天机 -bookname 超维入侵 -filename ./超维入侵.txt -tips=false
```

PS: `-tips=false` 的`=`号不能省略

**Comment by xingzhili2007** [comment]
## 测试
`./kaf -author 长月达平 -filename Re_从零开始的异世界生活.txt -match '外传|第.{1,4}卷'  -tips=false`
无法实现功能
![image](https://user-images.githubusercontent.com/60608543/116545657-44506100-a923-11eb-8ec7-9f06d01f61fc.png)
## 发现
经过再次测试，发现写-tips=0时可以
` ./kaf -author 长月达平 -filename Re_从零开始的异世界生活.txt -match '外传|第.{1,4}卷'  -tips=0`
![image](https://user-images.githubusercontent.com/60608543/116545764-6518b680-a923-11eb-8f72-244c099c9bbe.png)
## 哈哈哈
PS 一开始我的确把`=`忘了，嘿嘿 也希望作者表明~~方便白嫖~~

**Comment by xingzhili2007** [comment]
作者大大的这个软件非常好用的欧！

**Comment by ystyle** [comment]
添加到README里了
