### ISSUE TITLE
Mac 命令行， 转成mobi失败，希望能加上错误日志

### ISSUE THREAD

**Issue by guominfang** [ystyle/kaf-cli#8]
正在读取txt文件...
读取文件耗时: 177.413113ms

正在生成epub
正在生成电子书...
生成EPUB电子书耗时: 745.950082ms

使用第三方库生成azw3, 不保证所有样式都能正常显示
正在生成azw3...
生成Mobi电子书耗时: 114.61942ms

检测到Kindle格式转换器: kindlegen，正在把书籍转换成Kindle格式...
转换mobi比较花时间, 大约耗时1-10分钟, 请等待...
转换为Kindle格式耗时: 64.2µs

转换完成! 总耗时: 1.038733901s

**Comment by ystyle** [comment]
1. 检查kindlegen有没有可执行权限， 授权可执行`chmod +x kindlgen`
2. 授权后还不行，可以把kindlegen放path目录下再试试
3. 手工转换命令`kindlgen ebookname.epub`可以把epub转为mobi， 软件也是这么直接转的

**Comment by guominfang** [comment]
1、2、不成功

3是成功的，不过有很多警告

最终生成的mobi，大小翻倍了

**Comment by ystyle** [comment]
我没mac看不出来是啥问题，3能成功说明kindlegen下载时没损坏，没啥问题。
另外，标签问题不用关心，是epub3.0的兼容2.0原因，转换是没问题的（而且kindlegen是官方的）
大小翻倍问题可以在执行时加上`-dont_append_source`:

     kindlgen -dont_append_source ebookname.epub

这样就可以减小体积

-------
ps: 手工用kindlegen转换时，mobi的语言参数要自己设置， 参数是： `-locale zh`  zh是中文，en是英文

**Comment by guominfang** [comment]
@ystyle 是的，中午的时候，弄出来了，减少了一大部分，还是感谢你的工具
