### ISSUE TITLE
希望能增加文件名匹配书名和作者功能

### ISSUE THREAD

**Issue by lsl330** [ystyle/kaf-cli#9]
可以自动从文件名适配书名和作者么？
例如固定一种取名方式
如雪中悍刀行 - 烽火戏诸侯
或《雪中悍刀行》作者：烽火戏诸侯
拖曳的时候自动适配书名雪中悍刀行，作者烽火戏诸侯
这样就没必要用命令行生成了。
另外，我改名cover.png生成epub文件，在calibre里在线观看会看不到封面，不知道是软件的文件还是calibre的问题？

**Comment by ystyle** [comment]
最新的v1.2.2可以自动识别知轩藏书的txt文件名格式了
例: 《希灵帝国》（校对版全本）作者：远瞳.txt
